Adds Controls Config file as a JSON
ExOK/Celeste64 pull request #7
Opened 2024-01-30 07:44 UTC by Viv-0

Adds a controls config file as a JSON.
Tested against Windows 10 with Controller and Keyboard
Supports deadzones for joysticks/triggers
Please send feedback if you have concerns

2024-01-30 18:48 UTC, steviegt6 requested changes
Also lots of indentation inconsistencies.

2024-01-30 18:48 UTC, steviegt6 commented on Source/Assets.cs
> +#pragma warning restore CS8600
Why pragma instead of `!`?

2024-01-30 18:48 UTC, steviegt6 commented on Source/Controls.cs
> +#pragma warning disable CS8604
Why not just handle nullability?

2024-01-30 18:48 UTC, steviegt6 commented on Source/Controls.cs
> +    public static void HandleCustomControls(JsonNode root)
Would it not be better to deserialize to a type-checked object?

2024-01-30 18:48 UTC, steviegt6 commented on Source/Controls.cs
> +    public static void HandleCustomControls(JsonNode root)
This existing code is extremely volatile and will cause problems if even minor issues are present.

2024-01-30 20:17 UTC, NoelFB commented
Hey thanks for writing this all out! This is a great start, but I also agree with steviegt6 on a few issues:
 - Using null checks/handling null is better than using pragma's to ignore them. Ideally (aside from external libs) we wouldn't ignore any warnings.
 - I think creating a typed class to automatically serialize into might be worth doing. It might also make parsing the end data a lot easier. Since we're trimming the exe it will need a JsonSerializerContext but that's fairly trivial to do (see how [Save.cs does it](https://github.com/ExOK/Celeste64/blob/main/Source/Save.cs#L161))

2024-01-30 21:47 UTC, bitten2up commented
just tested this out, seems like the pause menu isn't working at least for keyboard

a quick look through the changes I'm not quite sure what the issue is

I have tried both a debug build and a release build on linux and both can't open it

2024-01-30 23:51 UTC, Viv-0 commented
Regarding this, I think in order to use a native Save structure it would require rewriting things in terms of solely buttons, similar to the structure within Celeste itself, i.e.:
`"MoveUp": { "Controller": ["LeftStickUp", "DPadUp"], "Keyboard": ["Up"] }`

I'm going to rewrite it terms of that but I'm not sure whether or not I should then include Deadzones for things like Joystick/Triggers

2024-01-31 17:11 UTC, steviegt6 commented
You can write your own (de)serializers.

2024-02-04 22:03 UTC, NoelFB commented
I ended up doing an implementation getting it working, based on the ideas here! Appreciate the first pass that was done, thank you!

It's still missing Mouse to aim, but I think that could be added as a separate PR (and probably part of Foster somehow).

2024-02-04 22:03 UTC, closed without merging